name: succulent_app
description: A modern habit tracker app with gamification - a simple, gamified version of a habit tracker.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  audioplayers: ^5.2.1
  flutter_bloc: ^8.1.2
  bloc: ^8.1.0
  equatable: ^2.0.5
  get_it: ^7.2.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  bloc_test: ^9.0.4
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/app-icon.svg
    - assets/splash-icon.svg
    - assets/audio/lofi_focus.mp3
    - assets/audio/focus_complete_chime.mp3
  fonts:
    - family: Brawler
      fonts:
        - asset: assets/fonts/Brawler-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app-icon.svg"
  remove_alpha_ios: true
